name: Publish Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Midnight every day

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authorize
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Release
        run: cd .scripts && sh ./package.sh
        # run: cd .scripts && python3 ./package.py
